"""empty message

Revision ID: 0e9e26cb8d11
Revises: d9dbe2dcefd3
Create Date: 2024-10-17 07:12:37.510097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9e26cb8d11'
down_revision = 'd9dbe2dcefd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_logged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_logged')

    # ### end Alembic commands ###
